backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Cerita & Berita"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Gambar Utama", name: "thumbnail", widget: "image", required: false }
      - { label: "Ringkasan", name: "summary", widget: "text" }
      - { label: "Isi", name: "body", widget: "markdown" }
